name: PHPUnit Tests via Composer

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Require php-cs-fixer
      run: composer require friendsofphp/php-cs-fixer --dev
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
#    - name: Run test suite
#      run: composer run-script test
    - name: Unit tests
      run: |
        ./vendor/bin/phpunit --no-coverage --colors=never
    - name: Psalm
      run: |
        ./vendor/bin/psalm --monochrome --no-progress --stats --show-info=false
    - name: phpstan
      run: |
        ./vendor/bin/phpstan --no-interaction --no-ansi analyse
    - name: Mess Detector
      run: |
        ./vendor/bin/phpmd src,tests text codesize,design,naming
    - name: php-cs-fixer
      run: |
        ./vendor/bin/php-cs-fixer fix -v --config=.php_cs.dist --using-cache=no --dry-run
