name: PHPUnit Tests via Composer

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
#    - name: Run test suite
#      run: composer run-script test
    - name: Unit tests
      run: phpunit --coverage-text
    - name: Psalm
      run: psalm
    - name: phpstan
      run: phpstan analyse
    - name: Mess Detector
      run: phpmd src text codesize,design,naming
